language: node_js
node_js:
  - "9"

branches:
  only:
    - master

install:
  - npm install

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm install -g @angular/cli
  - export CHROME_BIN=chromium-browser

jobs:
  include:
  - stage: test
    script: npm run lint
  - stage:
    script: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
  - stage: build
    script: npm run build

cache:
  yarn: true
  directories:
  - node_modules

notifications:
  email:
    - alexandre.lerat@gmail.com
    - r.olvera@laposte.net
