language: node_js
node_js:
  - "7"

branches:
  only:
    - master

script:
  - npm install

cache:
  yarn: true
  directories:
  - node_modules

notifications:
  email:
    - alexandre.lerat@gmail.com
